### PR TITLE
modernize uno.winui.samples (Currently uno 4.8)

### PR DESCRIPTION
**Pull request by inforithmics**
Trying to use new project template for uno.winui

### CODE REVIEW

**Comment by inforithmics** [comment]
Things done: 
1) upgarded to uno 4.8 (so that when an offical 4.9 comes out it can be easier upgraded (https://github.com/unoplatform/uno/issues/11944).
2) removed Skia.LinuxBuffer and Skia.wpf in uno.winui (aren't anymore in the default sample so i guess not supported anymore).
3) Some layout fix that it works on dark mode machines.

**Comment by inforithmics** [comment]
There is a bug in the uno platform for that i applied a workaround.
https://github.com/unoplatform/uno/issues/12013

So when this gets fixed too and an offical 4.9 release comes out this can be fixed and merged.

**Comment by inforithmics** [comment]
updated to uno.ui 4.8.39

**Comment by inforithmics** [comment]
I found a workaround for the dotnet build issue for dotnet build of Mapsui.Samples.Uno.WinUI.Windows.

**Review by pauldendulk — APPROVED** [review]
Thanks, it seems hard to get the all correct. There are now extra Directory.Build.props files. Is this generally the way to do this in Uno or is this a solution for the Mapsui project structure?

**Comment by inforithmics** [comment]
The extra directory.build.props come from the uno template.

**Pull request merged**
