### PR TITLE
Update RichTextKit

### PR DESCRIPTION
**Pull request by janusw**
In the light of recent RichtTextKit-related issues (like #1093), it's probably not a bad idea to update this library to the latest version.

Note that the version change does not seem to have any effect on the above issue. Also there don't seem to be any incompatible changes.

### CODE REVIEW

**Comment by m1dst** [comment]
I manually applied these updates and rebuilt the nuget which solved the issue I was having with the linker.  Would be great to get this change into an official pre-release nuget package.

**Review by m1dst — APPROVED** [review]

**Comment by janusw** [comment]
> I manually applied these updates and rebuilt the nuget which solved the issue I was having with the linker.

Good to hear, thanks for the comment!


> Would be great to get this change into an official pre-release nuget package.

Absolutely. @pauldendulk Can we please merge this into master?

**Comment by janusw** [comment]
I bumped the RichTextKit version once more, since another minor update was released in the meantime.

**Review by buu-huu — APPROVED** [review]
Makes sense

**Review by pauldendulk — APPROVED** [review]
Thanks for taking care of this.

**Pull request merged**
