### PR TITLE
Mapsui.UI.Uno.WinUI nuget package

### PR DESCRIPTION
**Pull request by inforithmics**
Uno.WinUI Target

### CODE REVIEW

**Comment by inforithmics** [comment]
I'll continue when this is in because Uno does not really like central package management for now.
https://github.com/Mapsui/Mapsui/pull/1657

**Comment by inforithmics** [comment]
The Windows sample works now, I have to fix ios,android, ...

**Comment by inforithmics** [comment]
Known Problems, When the Dark mode is enabled in the Browser the Text of the Menus is not visible in Mapsui.Samples.Uno.WinUI.Wasm

**Review by pauldendulk — APPROVED** [review]
Great to have Uno.WinUI as part of v4. By the time this release is stable Uno.WinUI will be the more important platform.

It is hard for me to properly review this, so I accept is as is.

**Comment by CliffAgius** [comment]
Hi All,
I am just looking at this for an UnoPlatform project and wondering if this is available yet or in a future release?

Cliff.

**Pull request merged**
