### PR TITLE
[WIP] Animatable

### PR DESCRIPTION
**Pull request by charlenni**
Made a new version of possible animation with implementing IAnimatable interface. It is possible to animate the Navigator, Layers, Features and Style.

@tmijieux Perhaps you could look into it, if the leaks are gone.

### CODE REVIEW

**Comment by inforithmics** [comment]
Overall Iike the Design. But would it be possible to clean ip the pull request (without the checkins from others) maybe recreate the pull request and Cherry picknthe relevant checkins. Because I have to Reviere Checkin for checkin

**Comment by pauldendulk** [comment]
@charlenni I will continue with my own  branch related to animation. This branch has something messed up with the diff which makes it hard to interpret. 

I looks like I will be using some UpdateAnimation method. But in my current plans it will not be a root interface that will be inherited by anything that could animation (so no check for an IAnimation interface). The alternative I had in mind is to have no UpdateAnimation at all, and just calculate at GetFeatures. That still may be a good option. Disadvantage: You still will need to check if an animation is running. And it makes it makes it harder to test. My plan now is to pass in a timerTick into the UpdateAnimation method. And also in the animation Start. Timer in are always problematic to test and in this way we can keep it out of the core functionality.

**Comment by charlenni** [comment]
Sorry, but it's not about implementation details, it's about basic things. I don't see why Viewport is better for animations than Navigator. For me, it just doesn't make sense. Viewport indicates what I see, Navigator moves the section I see. With PR, the viewport itself moves. And for the strict separation between the tasks of Viewport and Navigator, I still lack the coherent justification. Saving the function to stop the animations in Navigator is a bit too little for me. Especially since this is also called in Viewport.

Maybe you can explain the advantage a bit more.

**Comment by pauldendulk** [comment]
> Sorry, but it's not about implementation details, it's about basic things. I don't see why Viewport is better for animations than Navigator. For me, it just doesn't make sense. Viewport indicates what I see, Navigator moves the section I see. With PR, the viewport itself moves. And for the strict separation between the tasks of Viewport and Navigator, I still lack the coherent justification. Saving the function to stop the animations in Navigator is a bit too little for me. Especially since this is also called in Viewport.
> 
> Maybe you can explain the advantage a bit more.

See my comment here:
https://github.com/Mapsui/Mapsui/issues/1400#issuecomment-1003349079

Your comment here makes it seem as if Navigator could be the single source of truth for animations instead of Viewport.
- This would only possible if Viewport would be fully encapsulated. Which is not the case at all.
- Navigator in its previous state was far from the single source of truth for animation. This was not the case it all. Animation were managed from all kinds of places in the code.

The coming weeks I will spend the limited time I have primary on coding.

**Comment by pauldendulk** [comment]
One more thing. We need to have online video sessions.

**Pull request closed without merging**
