### PR TITLE
Updated to Skia Sharp 2.88.0-preview.209

### PR DESCRIPTION
**Pull request by inforithmics**

### CODE REVIEW

**Review by janusw — COMMENTED** [review]
What's the motivation for this? Does it fix an actual problem? Is it a good idea to use a preview version instead of a stable release?

**Comment by inforithmics** [comment]
This version of Skia sharp has for example fixed the nuget package size increase for Android.

**Comment by inforithmics** [comment]
Currently all the mapsui platforms that need it have this preview version and zhe others have 2.80.3. with my pending pull request ios and android will go to the preview version and only wpgf and forms stay at 2.80.2 so it is more a unification pull request to have all platforms on the same version.

**Comment by janusw** [comment]
> This version of Skia sharp has for example fixed the nuget package size increase for Android.

Ah, very good :) That is #1115.

However, it seems we're not even building a Mapsui.Android package any more (at least not in the AppVeyor builds ;)

**Comment by pauldendulk** [comment]
> However, it seems we're not even building a Mapsui.Android package any more (at least not in the AppVeyor builds ;)

Xamarin.Android and Xamarin.iOS will be added again in 4.0.0-beta.1. The old project format caused problems which I assume will be fixed in the new format.

**Comment by janusw** [comment]
> > However, it seems we're not even building a Mapsui.Android package any more (at least not in the AppVeyor builds ;)
> 
> Xamarin.Android and Xamarin.iOS will be added again in 4.0.0-beta.1. 

But 4.0.0-beta.1 has been released already! Do you mean 4.0.0-beta.2?

**Comment by pauldendulk** [comment]
> But 4.0.0-beta.1 has been released already! Do you mean 4.0.0-beta.2?

Yes, sorry you are right.

**Review by pauldendulk — APPROVED** [review]

**Pull request merged**
