### PR TITLE
Add virtual methods in EditManager

### PR DESCRIPTION
**Pull request by starnutoditopo**
Add virtual methods in EditManager, so that inherited classes can intervene on modified features.
See: https://github.com/Mapsui/Mapsui/issues/387#issuecomment-1890995785

### CODE REVIEW

**Review by pauldendulk — COMMENTED** [review]
Thanks you for you contribution. However in the current phase that we are in I don't want to work on extensions of the EditManager. 

The edit functionality was something I added for my specific purpose. It was at that point in the samples. This was because it was not well designed and not thought through well. 

The edit sample was a WPF app. This was becoming increasingly impractical because we support so many platforms. So, the editing code was converted to a platform independent solution, introducing the widgets, which makes it easier to maintain for us. It was however still a first version and in retrospect I think we should have marked it as experimental. Currently it does not function correctly for Avalonia for example. So, this is something we need to revisit so I don't want to add something on top of it.

Also, if we will support something like this it will probably through callbacks and not overrides of virtual methods. 

Related, this answer I posted on stackoverflow:
https://stackoverflow.com/questions/77807110/how-to-use-two-editingwidgets-in-c-sharp-mapsui-wpf-simultaneously/77807240#77807240

**Comment by pauldendulk** [comment]
See, my comment. I will close this PR for now. At some point we may want to add something like this. In general we appreciate feedback. A clear explanation of the use case you want to support is very welcome. We can take that into account rewriting the current code.

**Comment by starnutoditopo** [comment]
Thanks for your answer: it's useful to understand in which direction to go.

**Comment by starnutoditopo** [comment]
Then, `EditManager` could marked as `[Obsolete]`?

**Pull request closed without merging**
