### PR TITLE
Feature/unit tests to net core

### PR DESCRIPTION
**Pull request by pauldendulk**
Converted the unit tests to .net core
Merged the Mapsui.Desktop testes into the Mapsui tests.

### CODE REVIEW

**Comment by inforithmics** [comment]
I think following is missing in the appveyor.yml

**configuration:**
**- Release**
**platform:**
**- AnyCPU**

Because i got the pull request and it build with release any cpu. With that configration it should only build this configuration and work.

**Comment by pauldendulk** [comment]
Yes, I think that would solve it. I had the SKIA define setup only for debug and release but it built x64. Me latest commit adds the SKIA define to all platforms, but it's better remove them and just build release.

**Comment by inforithmics** [comment]
No Tests are shown in AppVeyor. See this Link for a Solution https://stackoverflow.com/questions/48235374/net-core-unit-tests-not-shown-in-appveyor-tests-window-and-badge

**Comment by pauldendulk** [comment]
> No Tests are shown in AppVeyor. See this Link for a Solution https://stackoverflow.com/questions/48235374/net-core-unit-tests-not-shown-in-appveyor-tests-window-and-badge

Good feedback, I had not noticed.

**Review by inforithmics — APPROVED** [review]

**Pull request merged**
