### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by inforithmics**
Updatet nuget and docfx and now the docs are generated

### CODE REVIEW

**Comment by inforithmics** [comment]
I have locally genereted the sites and with docfx serve docs (it displays now the api documentation)

**Comment by inforithmics** [comment]
https://github.com/Mapsui/Mapsui/pull/1740

Should fix this

**Review by pauldendulk — APPROVED** [review]
Thanks a lot for figuring this nasty thing out. What turned out to be the essential part? Btw, I was not aware of the docfx.json at all. I did create it myself at some point but completely forgot about it.

**Comment by inforithmics** [comment]
The two most important changes was.
1) include the new mapsui projects in docfx.json
2) install the same version of the dotnet sdk in the appveyor build task as in the regular build.

**Pull request merged**
