### PR TITLE
Refactoring of Widgets

### PR DESCRIPTION
**Pull request by charlenni**
@pauldendulk I'm so sorry, but it is a bigger PR than normal. But it seems, that all is connected with all.

I tried to refactor the Widgets. I removed the IWidgetExtended interface, because I think, it is only an extended ITouchableWidget (which I renamed from IWidgetTouchable for readability), and so I added the extra functions to this interface. If you now want, that a widget is touchable, you only add ITouchableWidget and implement the missing functions.

I made the inheritance of the widgets much clearer. TextBoxWidget inherits from BoxWidget, which inherits from TextBoxWidget. Both couldn't be touched. That belongs to TextButtonWidget. Widget by itself implements INotifyPropertyChanged, and it is used in all widgets. 

I sorted the widgets in folders to logical groups.

I introduced some more properties and enums for positioning of widgets. It is now possible to have widgets, that fill the whole screen or at an absolute position. Position is calculated by the Widget.UpdateEnvelope function that all widgets inherit.

The TouchableArea could be now only the widget or the whole screen.

I had to change some of the test images. Two of them missed the hyperlink, which is now included. The CustomWidget isn't visible in its test image for the sample. The others seem to be wrong. E.g. the ButtonSample defined a button with 64x64, but was much smaller before. So, I assume, that the new ones correct.

What is still missing is the text orientation inside a TextBoxWidget. I'm not sure, if this is too much effort for widgets. The same for Padding/Margin for left, top, right, bottom instead of x and y.

@janusw suggested in #2367 to have a grouping widget, so that more than one widget could be placed at a given position. I thought, if he already has one, I shouldn't invent the wheel twice. Perhaps, if this PR is merged, he can make a new PR.

### CODE REVIEW

**Comment by inforithmics** [comment]
@charlenni I did click the wrong button. So I apologize to removing the draft marker of this pull request.

**Comment by charlenni** [comment]
@inforithmics No problem. I thought in the first moment, I forgot this. But it seems, that this is now automatically done.

**Comment by pauldendulk** [comment]
@charlenni I am very sorry, but this PR is too big for me to review. It covers too many different things that we could all argue about. The bigger PRs I worked on in the past took a long time for me to review and in the end I was not fully happy with it but decided I had to merge at some point. The result is a gradual degradation of the code base. The MapControl touch code that I worked on to fix the touch issues of v4 is in desperate need of improvement. There is no one in particular to blame for that (except me because I am the maintainer), it is mostly because of the history of things. But now is the time to take a careful look at it. I am very motivated to improve things in V5. The [roadmap for V5](https://mapsui.com/documentation/roadmap.html#mapsui-5) is mostly targeted at that and that is what I want to focus on. Very basic things still don't work. The touch in current main simply does not work because the fixes in v4 need to be merged to main, but your changes also affect this code, so this complicates things. 

I suggest you close this PR and open a new one starting with some isolated changes. If you have other changes building on those changes do that in a new branch based on you previous PR. You could put those changes in a separate draft PR (or keep it local). Once the previous PR is merged you can update the follow-up MR and remove the draft.

**Comment by charlenni** [comment]
You are right. But I had time to do this and started with it, because it is an isolated part of the code.

My problem is, that when I start a refactoring and make a small change, wait 1 month for accepting the PR and then start with the next small part, I not remember what to do next. With this, we need a year of doing all the changes.

So I now drop this PR and try to do it in small portions. I hope, I get it so clear once again.

**Comment by pauldendulk** [comment]
> My problem is, that when I start a refactoring and make a small change, wait 1 month for accepting the PR and then start with the next small part, I not remember what to do next. With this, we need a year of doing all the changes.

I understand that problem. My intention is to do reviews of smaller PRs faster.

**Comment by charlenni** [comment]
Ok, I started to do this part by part, but it could get ugly in between ;-) I try to make an own PR for a small change and use this PR for the next PR. I hope this works and could make PR after PR. Don't know if this works.

**Pull request closed without merging**
