### PR TITLE
Added zoom in for double tap on Forms MapControl

### PR DESCRIPTION
**Pull request by charlenni**

### CODE REVIEW

**Comment by charlenni** [comment]
@pauldendulk Do you have a suggestion, why AppVeyor build fails? I used always the newest master and changed only a few lines.

**Comment by pauldendulk** [comment]
@charlenni I assume it is the itinero sample I added. Have to check.

**Comment by pauldendulk** [comment]
@charlenni  Removing the Itinero sample fixed the buildserver fail.

**Comment by pauldendulk** [comment]
@charlenni  Removing the Itinero sample fixed the buildserver fail.

**Pull request merged**
