### PR TITLE
define indent_size

### PR DESCRIPTION
**Pull request by rafntor**
if global settings in visual studio != 4 the current editorconfig will not help

### CODE REVIEW

**Review by inforithmics — APPROVED** [review]
Good catch this was missing in the .editorconfig

**Comment by inforithmics** [comment]
Can you define the indent dize for csproj to be 2. As in mapsui Developer Guidlined

**Comment by rafntor** [comment]
done! + fixup eto.csproj which was not 2

**Comment by inforithmics** [comment]
Thanks a lot. When the build is finished and green I'll merge this.

**Pull request merged**
