### PR TITLE
Add output of which MapRegressionTest is started

### PR DESCRIPTION
**Pull request by charlenni**
For me it is not clear which test is running before a crash happens. So I added a log entry with the name of the test.

### CODE REVIEW

**Comment by charlenni** [comment]
Added a log entry before and after the test.

This PR is in conjunction with #2402. For me it is not clear, if the crash happens while running th GeoTiff sample or a sample later. The crash occurs when a SymbolStyle should be drawn. But there isn't a SmbolStyle in the GeoTiff sample. So I added a start and end flag for each sample that runs to make it easier to find the right sample. If I have overseen this information and this PR is useless, then we can close it.

**Comment by inforithmics** [comment]
It crashed after "End MapRegressionTest MbTilesSample"

The next test would have been "Start MapRegressionTest RasterizingTileLayerGeoJsonSample"

So there are two possible Areas.
1. A Memory Leak/Corruption in Sqlite (Because of MbTiles)
2. A Memory Leak/Corruption in RasterizingTileLayer

**Comment by charlenni** [comment]
@inforithmics Where did you see this? Could you reproduce this locally or do you have a protocol where it could be seen?

**Comment by inforithmics** [comment]
I saw this on the last GitHub action build. I couldn‘t reproduce locally. I‘m thinking about running the tests locally 10 times or more so if there is a problem in one test it should sow up

**Comment by charlenni** [comment]
Ok, I got the error locally by running test "RasterizingTileLayerGeoJsonSample" in debug mode.

grafik

I would say, that the line 168 of file "SymbolStyleRenderer.cs", which is

        var path = vectorCache.GetOrCreatePath(symbolStyle.SymbolType, CreatePath);

make the trouble. All could be expected except `path` when the test crashes.

**Comment by charlenni** [comment]
Ok, seems to me as a racing condition. From 10 times to run, it fails around 6 times.

**Comment by inforithmics** [comment]
I tried this branch and made a loop with 100 calls and it didn't crash on my computer. I tested it after I merged main into this branch. So it is using now SkiaSharp 2.88.7.

**Comment by charlenni** [comment]
I run only this test in debug mode. Will try it again with the new version.

**Comment by charlenni** [comment]
I run it 7 times with no problems. The 8th crashed.

**Comment by charlenni** [comment]
Run it in debug mode and do something beside this. When I close the test tree after I start the test, then it crashes.

**Comment by inforithmics** [comment]
I could now reproduce it. Open the Editing Sample in Avalonia and move the Shape around then it crashes. So I can fix it from there.

**Comment by charlenni** [comment]
How can I help?

**Comment by inforithmics** [comment]
I found out why it doesn't work every drawn Element in SkiaSharp should have it's own skpath.
1. Because of caching the All Symbols had the same SkPath so giving every symbol it's own skpath improved things considerably.
2. Clipping shouldn't be done on a cached path, but the clipped path should be cached.
```
               canvas.ClipPath(linePath);
```

**Comment by pauldendulk** [comment]
Great you are looking into these hard to reproduce issues and not giving up on it. The bugs that are the hardest to find cause the most problems in the long run. Often people tend to ignore them because they don't happen very often.

**Comment by charlenni** [comment]
@pauldendulk in our case they happen very often.

@inforithmics When you look into SkPath of the Skia [documentation](https://api.skia.org/classSkPath.html), go down to the "Detail description". The last line suggest that SkPath is threadbare if you call `SkPath::updateBoundsCache` (read also [this](https://api.skia.org/classSkPath.html#a6de7de42175fe3ce5ff92f3d2267ec2d)). Perhaps we should try this when writing the SKPath to the cache?

**Comment by charlenni** [comment]
Ok, looked into SkiaSharp implementation, but couldn't find the `UpdateBoundsCache` function. So it isn't there and if we like to have it, we must create it. Perhaps a PR?

By investigating further, the `SkPath::updateBoundsCache()` is internal only a `SkPath->getBounds()` call (see [here](https://github.com/google/skia/blob/39bb9c35b840a4dedfc3c86316a3c77c21e905eb/include/core/SkPath.h#L501)). So it would be enough to add a call like this

        if (path is SKPath p) _ = p.Bounds;

after creating the path. But it doesn't work.

Perhaps related with [this](https://github.com/mono/SkiaSharp/issues/571)? And an [message](https://groups.google.com/g/skia-discuss/c/-G1cyl1QD9E) (quite old) or [this](https://issues.skia.org/issues/40036954) or [this](https://issuetracker.google.com/issues/36925032#comment5) about thread safeness of Skia.

I would say, caching for same pathes to one path isn't a good idea.

**Comment by inforithmics** [comment]
Pull request with my learnings and Bugfixes (does not work yet 100%)
https://github.com/Mapsui/Mapsui/pull/2425

**Comment by pauldendulk** [comment]
I am going to merge this PR which just adds console logging. We might want to go back to this thread to see what is discussed.

**Review by pauldendulk — APPROVED** [review]
Yes, good idea, its a puzzle for me every time too.

**Pull request merged**
