### PR TITLE
Replaced Mapsui.Utilities.Timer with System.Threading.Timer

### PR DESCRIPTION
**Pull request by charlenni**
Regarding the AnimatedPointsSample: Shouldn't the points be animated between the timer ticks? I cant reproduce this. Not with the new timer, not with the old timer.

### CODE REVIEW

**Comment by pauldendulk** [comment]
It think this is an issue with the random generator logic. Introduces when doing some refactoring some months ago. They do animate initially don't they?

**Comment by charlenni** [comment]
They start in the center, than go animated to their places. After this initial animation, only one feature vanish and another pops up.

**Comment by pauldendulk** [comment]
Yes. I think the random generator restarts with same seed.

**Comment by charlenni** [comment]
You are right. That is the problem.

**Pull request merged**
