### PR TITLE
Use Git Lfs for Regression png and sqlite Files 

### PR DESCRIPTION
**Pull request by inforithmics**
Use Git Lfs for Regression png and sqlite Files 

I used following git lfs commands
```
git lfs install
git lfs track "Tests/Mapsui.Rendering.Skia.Tests/**/*.png"
git lfs track "Tests/Mapsui.Rendering.Skia.Tests/**/*.sqlite"

git lfs migrate import --include="Tests/Mapsui.Rendering.Skia.Tests/**/*.png" --message="Migrate Binary Data"
git lfs migrate import --include="Tests/Mapsui.Rendering.Skia.Tests/**/*.sqlite" --message="Migrate Binary Data"
```

### CODE REVIEW

**Comment by inforithmics** [comment]
When this gets merged I will redo the SkiaSharp 3 pull request, because there a lot of images got updated.
https://github.com/Mapsui/Mapsui/pull/2603

Maybe I could add a check before running the regression test to see if an lfs checkout was made.

**Review by pauldendulk — COMMENTED** [review]
How should I interpret the diff of this PR. All the images are marked as changed, but not deleted. I can't see the diff on github. In what way are they changed?

**Comment by pauldendulk** [comment]
I received this email from support@github.com:

```console
We wanted to let you know that you’ve used 80% of your data plan for Git LFS on the organization Mapsui. No immediate action is necessary, but you might want to consider purchasing additional data packs to cover your bandwidth and storage usage:

  https://github.com/organizations/Mapsui/billing/data/upgrade

Current usage as of 26 Oct 2024 08:28AM UTC:

  Bandwidth: 0.81 GB / 1 GB (81%)
  Storage: 0.08 GB / 1 GB (8%)
```

I don't even know how we use it, since the branch is in your own repository. Guess this is only because of the build server building your branch. Storage is no problem. But will happen if the bandwidth limit is reached? Will it stop working?

This is what chatgpt says:
> Bandwidth Restrictions: GitHub restricts bandwidth usage for Git LFS to 1 GB per month for free accounts. Exceeding this will prevent further downloads of LFS objects until the next month or until additional bandwidth is purchased.

That would mean it is unusable.

**Comment by pauldendulk** [comment]
I now received this email 😕

```
Git LFS has been disabled on the organization Mapsui because you’ve exceeded your data plan by at least 150%. Please purchase additional data packs to cover your bandwidth and storage usage:

  https://github.com/organizations/Mapsui/billing/data/upgrade

Current usage as of 29 Oct 2024 04:26PM UTC:

  Bandwidth: 1.5 GB / 1 GB (150%)
  Storage: 0.08 GB / 1 GB (8%)
```

**Comment by inforithmics** [comment]
I didn‘t know that the Bandwith is this restlricted. Because the purpose is to Store large Objekts sometimes 100mb and more Bit with this restriction it won‘t work. A possibility is to Cache the lfs objects Like the NuGet packages but this gets to complicated for my Taste.

**Comment by inforithmics** [comment]
> How should I interpret the diff of this PR. All the images are marked as changed, but not deleted. I can't see the diff on github. In what way are they changed?

The png Images Are replaced by links to the png Images in lfs. So that‘s the diff. and lfs Checkouz replaces the lfs links with the real images.

**Pull request closed without merging**
