### PR TITLE
MapBuilder

### PR DESCRIPTION
**Pull request by pauldendulk**
Recreating the MR by reverting the revert

### CODE REVIEW

**Comment by pauldendulk** [comment]
Sorry for messing this up. Let's continue with this revert of the revert and pretend that nothing happend. 

@charlenni A number of .csproj files were added. Was this intended? (or was this caused by me messing up? I don't think so because I see them also in the original).

**Comment by charlenni** [comment]
Sorry, no, I didn‘t changed there anything. Is it possible to revert this. As revert from the revert ;-)

**Comment by pauldendulk** [comment]
> Sorry, no, I didn‘t changed there anything. Is it possible to revert this. As revert from the revert ;-)

It would be a revert from a revert from a revert! If you checkout this branch of the Mapsui project you could delete the files there, `git checkout revert-2342-revert-2341-MapBuilder`. You have rights to push to branches of this repository except master.

**Comment by charlenni** [comment]
I closed this, because I couldn't correct it. Git isn't my best friend. I opened a new one. See #2346.

**Pull request closed without merging**
