### PR TITLE
Release 4.0.0-beta.6

### PR DESCRIPTION
**Pull request by janusw**
@pauldendulk @inforithmics When would be a good point to push out a 4.0.0-beta.6 release ?

The last beta release (beta.5) is 5 months old by now.
The last beta release that was working for me (beta.3) is 8 months old by now.
Other people have requested a new beta package as well.

Maybe one should also start thinking towards a final 4.0 release (cf #1759)? What do we want to have in there?

Many new sub-packages have been created in the last months, which have not yet seen a stable release at all:
* Mapsui.Maui
* Mapsui.Avalonia
* Mapsui.ArcGIS
* Mapsui.Eto
* Mapsui.Uno

Mapsui.Maui alone would be enough of a reason for publishing a "stable" version IMHO (once it's stable) ...

### CODE REVIEW

**Comment by inforithmics** [comment]
I'm for a new Release: I have several open Pull requests I'd like to get merged.

Fixing appveyor build:
https://github.com/Mapsui/Mapsui/pull/1754

Samples Fixes: 
I made the Desktop Samples work on all platforms.
https://github.com/Mapsui/Mapsui/pull/1757

ArcGis Fixes:
Fixed Warnings and in the Process I fixed some ArcGis Bugs.
https://github.com/Mapsui/Mapsui/pull/1751

Net 7 Target:
Because Maui and Wasm is not Version Compatible .Net6 and .NET7 need to have seperate targets.
https://github.com/Mapsui/Mapsui/pull/1749

**Comment by pauldendulk** [comment]
I will make some time to look into this next Wednesday.

**Comment by pauldendulk** [comment]
I always unload Uno. I now get compile errors on Mapsui.UI.Uno. I tried uno-check, but this did not fix it. What should I install? 

```console
"c:\code\github\mapsui4\Mapsui.UI.Uno\Mapsui.UI.Uno.csproj" (default target) (1) ->
"c:\code\github\mapsui4\Mapsui.UI.Uno\Mapsui.UI.Uno.csproj" (Build target) (1:13) ->
(CoreCompile target) ->
  c:\code\github\mapsui4\Mapsui.UI.WinUI\MapControl.cs(39,45): error CS0234: The type or namespace name 'HorizontalAlig
nment' does not exist in the namespace 'Windows.UI.Xaml' (are you missing an assembly reference?) [c:\code\github\mapsu
i4\Mapsui.UI.Uno\Mapsui.UI.Uno.csproj::TargetFramework=uap10.0.19041]
  c:\code\github\mapsui4\Mapsui.UI.WinUI\MapControl.cs(40,43): error CS0234: The type or namespace name 'VerticalAlignm
ent' does not exist in the namespace 'Windows.UI.Xaml' (are you missing an assembly reference?) [c:\code\github\mapsui4
\Mapsui.UI.Uno\Mapsui.UI.Uno.csproj::TargetFramework=uap10.0.19041]
  c:\code\github\mapsui4\Mapsui.UI.WinUI\MapControl.cs(11,15): error CS0234: The type or namespace name 'Devices' does
not exist in the namespace 'Windows' (are you missing an assembly reference?) [c:\code\github\mapsui4\Mapsui.UI.Uno\Map
sui.UI.Uno.csproj::TargetFramework=uap10.0.19041]
  c:\code\github\mapsui4\Mapsui.UI.WinUI\MapControl.cs(13,15): error CS0234: The type or namespace name 'System' does n
ot exist in the namespace 'Windows' (are you missing an assembly reference?) [c:\code\github\mapsui4\Mapsui.UI.Uno\Maps
ui.UI.Uno.csproj::TargetFramework=uap10.0.19041]
```

btw Mapsui.UI.Uno.WinUI does build.

**Comment by janusw** [comment]
> I always unload Uno. I now get compile errors on Mapsui.UI.Uno. I tried uno-check, but this did not fix it. What should I install?

Hi @pauldendulk, it should not be necessary for you to build things manually. GitHub Actions does it all, and it seems to work flawlessly.

In order to obtain properly-versioned nupkgs, you could simply do the following:
1. Merge this branch to master (preferably via command line, not the GitHub web interface).
2. Tag the resulting merge-commit as "4.0.0-beta.6" (`git tag -a 4.0.0-beta.6 -m "Release 4.0.0-beta.6"`).
3. Push both, the new master branch and the tag, to the GitHub remote together (via `git push origin master --tags` or similar).

As a result, GHA will run and produce nuget packages with version "4.0.0-beta.6", which you can upload to nuget.org. (If you cannot push both together, you can also re-run the GHA job manually after setting the tag.)

I'm using this strategy with other projects, and it removes the need for building anything manually. IMHO, it is even preferable, since a CI build is done in a cleaner and more controlled environment, which makes it safer and more reproducible.

**Comment by inforithmics** [comment]
I think The "Universal Windows Platform Development" Workload needs to be installed

image

Especially the Windows 10 SDK 10.0.19041.0

in  the Visual Studio installer

image

This is because Uno tries to stay compatible to UWP whereas Uno.WinUI tries to stay compatible to WinUI

**Comment by janusw** [comment]
> I'm for a new Release: I have several open Pull requests I'd like to get merged.

@inforithmics Seems like all of those are merged by now.


> I will make some time to look into this next Wednesday.

@pauldendulk  It's Wednesday again. 😝

If I can be of any help with packaging etc, just let me know.

**Comment by pauldendulk** [comment]
Sorry, no time at all this week. I'll try again next week. 😟☹️😭

**Comment by pauldendulk** [comment]
btw, as a regular pro all my releases everywhere are fully automated, except for in Mapsui. Setting it up does take some time which I did not have so far, and I don't use github actions in any of my other projects, so there are a few things I need to figure out. For instance how to work with secrets. I need to store the nuget api key and use that to push the nugets. I am sure this is all not very hard but perhaps you can help here.

**Comment by janusw** [comment]
> btw, as a regular pro all my releases everywhere are fully automated, except for in Mapsui. Setting it up does take some time which I did not have so far, and I don't use github actions in any of my other projects, so there are a few things I need to figure out. For instance how to work with secrets. I need to store the nuget api key and use that to push the nugets. I am sure this is all not very hard but perhaps you can help here.

I have never done this with GHA either, but I guess this should help: https://docs.github.com/en/actions/security-guides/encrypted-secrets

**Comment by pauldendulk** [comment]
An update. I have been experimenting with publishing with nugets in a test project. Got it to work. Still need to apply this to Mapsui. 

Perhaps I should release with the script before that. The local build works after the updates.

**Review by pauldendulk — APPROVED** [review]

**Pull request merged**
