### PR TITLE
Add Newtonsoft to Mapsui.Samples.Forms.Wpf

### PR DESCRIPTION
**Pull request by charlenni**

### CODE REVIEW

**Comment by pauldendulk** [comment]
Why was this needed?

**Comment by charlenni** [comment]
Good question. Newtonsoft is always in the last project installed. In this case in the samples. But up to now, no one checked the Forms.WPF sample. I checked it now, because the UWP samples lacks of the certificate ;).

**Comment by charlenni** [comment]
Btw. both UWP samples (normal and Forms).

**Comment by charlenni** [comment]
Oh, you did this allready. Thank you for your work.

**Comment by pauldendulk** [comment]
But what is failing without the package?

**Comment by charlenni** [comment]
Oh, you only updated the normal samples for UWP, not the Forms version.

**Comment by pauldendulk** [comment]
> Oh, you only updated the normal samples for UWP, not the Forms version.

You are referring to the .pfx update?

**Comment by charlenni** [comment]
Yes. And failing was Mapsui.Samples.Forms.Wpf.

**Comment by charlenni** [comment]
To reproduce the problem with Newtonsoft start the Mapsui.Samples.Forms.Wpf sample and select <Geometries><1 Points>. Than you get an error.

**Comment by pauldendulk** [comment]
> To reproduce the problem with Newtonsoft start the Mapsui.Samples.Forms.Wpf sample and select <1 Points>. Than you get an error.

ah yes, I see it fail, but why, the samples project has a reference to newtonsoft and it compiles, that should be enough.

**Comment by charlenni** [comment]
I assume, that the DLL isn't copied to the correct folder. So it compiles, but when running, it fails.

**Comment by pauldendulk** [comment]
> I assume, that the DLL isn't copied to the correct folder. So it compiles, but when running, it fails.

Perhaps it it seems to me this caused by an error, either in our csproj or in Xamarin.Forms. Since I don't know what causes it I will simple merge.

**Pull request merged**
