### PR TITLE
New callout create uwp fix

### PR DESCRIPTION
**Pull request by jasells**
this avoids the dead-lock condition when creating a pin's callout on UWP.

### CODE REVIEW

**Comment by jasells** [comment]
This **_DOES_** address #606, but relies on version SkiaSharp.Forms.Views v 1.68.2-preview.17 changing the source thread of the tap events from `SKGLView` being the Main/UI thread on UWP/WPF.

This change makes the `SKGLView` behave idiomatically correct for Windows platforms.

**Comment by charlenni** [comment]
Thank you for your support.

But meanwhile I did a complete redesign of callouts. You can find the code [here](https://github.com/charlenni/Mapsui/tree/NativeCallout). The new implementation has advantages, but also disadvantages, but it doesn't rely on Xamarin.Forms. So there are no problems with any events ;-)

Thank you very much for your help to understand where the problems came from.

**Comment by jasells** [comment]
> Thank you for your support.
> But meanwhile I did a complete redesign of callouts. You can find the code here. The new implementation has advantages, but also disadvantages, but it doesn't rely on Xamarin.Forms. So there are no problems with any events ;-)
> Thank you very much for your help to understand where the problems came from.

I'll take a look!

But master still uses the Forms-based Callouts...

**Comment by jasells** [comment]
As soon as this can get through, I have some related changes to make code maintenance easier on callouts, regardless of impl.

**Comment by jasells** [comment]
> This DOES address #606, but relies on version SkiaSharp.Forms.Views v 1.68.2-preview.17 changing the source thread of the tap events from SKGLView to be the Main/UI thread on UWP/WPF.
> This change makes the SKGLView behave idiomatically correct for Windows platforms, in regard to the thread raising UI events like tap, touch, mouse move, etc, IS the UI thread.

@pauldendulk  To be clear, #606 exists in latest master *because* SkiSharp.Forms.Views  v 1.68.2-preview.17 fires tap events on Main/UI thread, but `MapView.CreateCallout()` puts the calling thread into a spin wait until the main thread creates the callout, leading to endless spin wait.  

No sync is needed now that Tap events are fired on main thread on UWP.

**Pull request merged**
