### PR TITLE
Add old viewport in ViewportChanged event arguments

### PR DESCRIPTION
**Pull request by charlenni**
Until now, the old Viewport wasn't available after changing some of the settings. With this change, the ViewportChanged event has its own EventArgs, which contain the Viewport from before the change. So it is possible to check, what changed in between.

This is regarding #2280.

### CODE REVIEW

**Comment by pauldendulk** [comment]
Sorry but I have caused conflicts to this PR by merging some big changes.

**Comment by charlenni** [comment]
Solved them

**Review by pauldendulk — APPROVED** [review]
Great.

I guess logical next request will be to have the current viewport state as well. Should we? Lets just take this step first.

**Comment by charlenni** [comment]
But why? I don't see any advantage for this.

**Comment by pauldendulk** [comment]
You could do a comparison locally with no need to have access to the current viewport, but indeed, there is no real need because there is an alternative solution. So, let's keep it like it is now.

**Pull request merged**
