### PR TITLE
Feature/use pixeldensity in rasterizinglayer

### PR DESCRIPTION
**Pull request by pauldendulk**

### CODE REVIEW

**Comment by pauldendulk** [comment]
@tonyfonager This is something I started two weeks ago. Should have been a quick thing but I could not spend much time on it. The rasterizinglayer is now pixelperfect.

After struggling with passing in the PixelDensity I now think I would be best if the MapRenderer is in charge of rasterization. Perhaps just a boolean on the layer. It could even be determined dynamic based on how long it takes to draw a layer. 

@charlenni This also affects the snapshot functionality that you added. After this fix the quality should now be the same as what you see on screen.

**Comment by pauldendulk** [comment]
Below is a image comparison of the rasterized and direct-draw image. The image below shows the differences in purple highlighting. There is only some in the top bar, none in the image itself.

image

@tonyfonager btw, you mentioned some wiggling in the position of the features wrt the background. They may have been caused (or at least enhanced) by a rounding error that was fixed with this.

**Comment by tonyfonager** [comment]
Its SOOO cool and great news. I will test it first thing tomorrow. Thanks alot Paul.

**Comment by tonyfonager** [comment]
If I have to test this, I have to leave the "research" branch with the SkiaSharp fix, correct ?

**Comment by pauldendulk** [comment]
Yes, it is only master. There is no need to hurry though. Testing skiasharp is more important now.

**Comment by tonyfonager** [comment]
I have had NO crashes so far - just sat with the iOS version on a device for 30 minutes, zooming, panning and absolutely no issues 👍

**Pull request merged**
