### PR TITLE
Move WFS-related code from Mapsui.Desktop into Mapsui

### PR DESCRIPTION
**Pull request by janusw**
* move WfsProvider into Mapsui.Providers
* move WfsSample into Mapsui.Samples.Common.Maps

### CODE REVIEW

**Comment by charlenni** [comment]
@janusw Is this PR needed, if @JBou try to make a PR with his efforts of the last two weeks?

**Comment by janusw** [comment]
> @janusw Is this PR needed, if @JBou try to make a PR with his efforts of the last two weeks?

Not sure. I was assuming he'd mostly make functionality-wise modifications to the WFS code, without moving it. If that's the case, then I think the PR here still makes sense. @JBou should easily be able to rebase his branch to this here, and git will notice that the files were moved and apply the modifications in the new place (git is sufficiently smart with such things). @JBou, maybe you can comment?

**Comment by JBou** [comment]
Yes I am trying to rebase to your branch 👍

**Comment by JBou** [comment]
I successfully rebased. You can merge this if you want. I will create my PR now :)

**Comment by janusw** [comment]
> I successfully rebased. You can merge this if you want. I will create my PR now :)

Great! Please reference #1072.

**Comment by pauldendulk** [comment]
@janusw @JBou I assume this can be closed now there is a new PR?

**Comment by JBou** [comment]
We can also already merge this and merge my PR afterwards when it's finished. What do you think @janusw ?

**Comment by janusw** [comment]
Doesn't really matter. Since my commits are included in #1074, everything can just be merged together, so I'll close this one.

**Pull request closed without merging**
