### PR TITLE
Upgrade Microsoft.Net.Compilers.Toolset to 4.6.0

### PR DESCRIPTION
**Pull request by pauldendulk**
After upgrading my Visual Studio yesterday to the latest I got this error:
```console
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS9057	The analyzer assembly 'C:\Program Files\dotnet\sdk\7.0.302\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll' references version '4.6.0.0' of the compiler, which is newer than the currently running version '4.5.0.0'.	Mapsui (netstandard2.0)		
```
The upgrade fixed it.

### CODE REVIEW

**Comment by inforithmics** [comment]
The error message means something in the windows app sdk isn't anmyore compatbile i'll upgrade the analyzers and the windows app sdk to see if it runs

**Comment by inforithmics** [comment]
intrestingly locally this works. So it seems that to merge this upgrade we have to wait until the Image gets upgraded to Visual Studio 17.6

**Comment by inforithmics** [comment]
<RunApiCompat>false</RunApiCompat> was the fix for the build.

Should I make a second pull request with the changes for winui (removing workarounds, and fixing dark mode).

**Comment by pauldendulk** [comment]
Thanks a lot for helping out. This is the kind of issue I struggle with. I am very eager to upgrade everything to .NET 6. Very unfortunate that simply upgrading VS breaks the build. That should not happen.

Fine that just work with me in the same MR.

The release nugets actions still fails for this branch on `dotnet workload install maui macos android ios maccatalyst wasm-tools wasm-tools-net6`, but that command is identical to the windows build:
https://github.com/Mapsui/Mapsui/actions/runs/5097832115/jobs/9164604923

**Comment by inforithmics** [comment]
I forget to add the .net 7 install to the release yml. will do it now.

**Comment by pauldendulk** [comment]
> I forget to add the .net 7 install to the release yml. will do it now.

Thanks, that fixed it. Now there is an error later in the script 
`error MSB4018: The "Microsoft.DotNet.ApiCompat.Task.ValidatePackageTask" task failed unexpectedly` https://github.com/Mapsui/Mapsui/actions/runs/5103128241/jobs/9173132346#step:10:479

**Comment by inforithmics** [comment]
I set 
`    <RunApiCompat>false</RunApiCompat>`
no in 
Directory.Build.props
so that in every project the runapicompat task is disabled. (We don't use it currently anyway). The task checks for breaking changes between Versions. It enforces the Correct Version numbering for Releases.

**Comment by pauldendulk** [comment]
> I set 
` <RunApiCompat>false</RunApiCompat>` 
now in Directory.Build.props so that in every project the runapicompat task is disabled. (We don't use it currently anyway). The task checks for breaking changes between Versions. It enforces the Correct Version numbering for Releases.

I know nothing about this. Read a bit now here: https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/overview

> So can you try again?

Fixed it!

**Pull request merged**
