### PR TITLE
eto: user-setable mouse&key for zoom&drag operations

### PR DESCRIPTION
**Pull request by rafntor**

### CODE REVIEW

**Review by inforithmics — APPROVED** [review]
The merge conflict needs to be adressed

**Comment by rafntor** [comment]
Thanks for all the help ;-)
Is there an ETA on next nuget-release?

**Comment by pauldendulk** [comment]
> Is there an ETA on next nuget-release?

No, but there is a 92 % change that it will be released between now and two weeks.

**Comment by pauldendulk** [comment]
> Thanks for all the help ;-) Is there an ETA on next nuget-release?

btw, there are nugets of the latest build. More info [here](https://mapsui.com/documentation/nuget-of-latest-build.html).

**Comment by pauldendulk** [comment]
@rafntor 4.0.0-beta.2 has been released which included Mapsui.Eto. https://www.nuget.org/packages/Mapsui.Eto.

Perhaps you can check if it works as expected. And if you do perhaps you can create a little getting started for it. Something like this https://github.com/Mapsui/Mapsui/blob/master/docfx/documentation/getting-started-wpf.md. I created an empty page here: https://github.com/Mapsui/Mapsui/blob/master/docfx/documentation/getting-started-eto.md.

**Pull request merged**
