### PR TITLE
Improve edit sample (With Buttons and Layer selection with Widget instead of real Buttons)

### PR DESCRIPTION
**Pull request by inforithmics**

### CODE REVIEW

**Comment by inforithmics** [comment]
I have now migrated all the Editing Functionality to the Sample. So I could remove now the Wpf.Editing Sample project.

**Comment by inforithmics** [comment]
Things done:
A fully fleged Editing Sample:
Fixed Widget were not rendered in Skia Render Tests.
Added TextBoxWidgetRenderer
Added BoxWidget and Renderer.
Improved ButtonWidget to Allow Text.

**Review by pauldendulk — APPROVED** [review]
Great, thanks for implementing the TexBoxWidgetRenderer reusing the HyperlinkWidgetRenderer.

**Comment by pauldendulk** [comment]
> I have now migrated all the Editing Functionality to the Sample. So I could remove now the Wpf.Editing Sample project. what's your opinion @pauldendulk

Yes, please! Deleting is the best thing you can do in software development, and also the most satisfying, enjoy!

**Pull request merged**
