### PR TITLE
fixing mousewheel scrolling

### PR DESCRIPTION
**Pull request by inforithmics**

### CODE REVIEW

**Review by pauldendulk — APPROVED** [review]
👍

**Comment by pauldendulk** [comment]
@inforithmics The mouse wheel scroll fix has no effect in my development environment. Do you know why this is? I ask because I need to suppress touch as well, which has no effect so far, but it could be because of my development environment too.

**Comment by inforithmics** [comment]
I would suggest to install newest .NET 7 SDK and call dotnet workload update on the commandline. I discovered that Scrolling with mouse does not work in firefox (but the scroll page suppression does).

**Comment by pauldendulk** [comment]
@inforithmics Thanks, got it work. Not sure what it was in the end. Also updated Visual Studio.

**Pull request merged**
