### PR TITLE
Touch Handling in Avalonia (Zoom and Rotation)

### PR DESCRIPTION
**Pull request by inforithmics**

### CODE REVIEW

**Comment by inforithmics** [comment]
The behavior of the Clockwise rotation I discovered it too.
https://github.com/Mapsui/Mapsui/issues/2090

**Comment by slater1** [comment]
Anything I can do to help this along? Really anticipating touch working on Android / iOS!

**Comment by inforithmics** [comment]
You could download the artifact and Test the nuget package. And if you find issues report them here or give a thumbs up.

**Comment by slater1** [comment]
I ran my Android app referencing the [latest artifact](https://github.com/Mapsui/Mapsui/actions/runs/5948164467). There's a couple of issues, see the video and comments below.

I'll try on iOS later today when wife gets home. She has the iPhone.

https://youtube.com/shorts/iVdfGTUhW7M?feature=share

Video contents in sequence:

- single-finger pan. Looks good.
- two-finger rotate, CCW and CW. Looks good.
- two finger zoom, our and in. Looks good.
- single-finger zoom and rotate (!)
- two-finger attempt to zoom and rotate (failed)

Notes:

-  First pinch and zoom works fine
- After releasing the first pinch and zoom, a single touch also pinches and zooms.
- After that single touch is released, cannot pinch and zoom with either single-finger or two-finger touch.
- Issue does not resolve until app is restarted (presumably a new MapContol would be enough)

**Comment by inforithmics** [comment]
Thanks for the tests. I think somehow a touch wasn't released. That's why there was a single touch zoom. I'll investigate it.

**Comment by inforithmics** [comment]
Could you provide a not working sample project. Because I tried it with Mapsui Avalonia Android Sample Project and there it works without problems.

**Comment by inforithmics** [comment]
@slater1 I found an Event where I need to Clear the TouchState, maybe it works now better for you?

**Comment by slater1** [comment]
Downloaded the [artifact ](https://github.com/Mapsui/Mapsui/actions/runs/5980554279) that built just a few minutes ago, and it seems to be working on Android!

I lied, didn't get to try iOS today. Will aim to get back on that this weekend.

Thanks for the work!

**Comment by slater1** [comment]
I can confirm that map pinch zoom and rotate now works on iOS, at least on iPhone 14 iOS 16.4.

**Comment by pauldendulk** [comment]
I need more time for this one. Touch is implemented in different ways on the various platforms. This PR shares more of the code which is a good thing but still some platforms, like Blazor, have a very different implementation. I would like to have a bigger rewrite of the touch handling but it will take some thought. A few thing I worry about in the code reused in this PR is:
- I am not sure if we should handle things like ShortTap, ShortClick, DelayTap, LongTap. I would prefer it if the platform handles it. 
- The _touches array is a stateful thing and if there is an error in keeping track of the state this gets problematic. We had a problem with this recently where some even in Maui was not triggered and because of this some touch point was not removed. Perhaps there is no way around it though. But if the platform solves this for us it would make things easier.
- Some of the shared code should perhaps we in components which could be used in the various MapControls, but would not have to be in the Shared MapControl.

The remarks about are not suggestions for improvement because I don't know myself what is the best way to improve it.

**Comment by inforithmics** [comment]
@pauldendulk I think I will make another pull request with changes only in Avalonia. So this would be less risk. The touchhandling Unifcation can be done in a seperate pull request.

**Comment by inforithmics** [comment]
New Pull Request (I copied the code from this pull request and added the missing functions (that where in MapControl Shared)) So this pull request is the same as this but without changes in other controls or in the Shared MapControl.
https://github.com/Mapsui/Mapsui/pull/2159

**Pull request closed without merging**
