### PR TITLE
Avalonia.MapControl: fix zoom with touchpad on MacOS & Linux

### PR DESCRIPTION
**Pull request by yapus**
Contrary to integer +1/-1 "Y" deltas sent by ordinary mouse devices, on MacOS & Linux, touchpads emulate the scroll wheel by dragging two fingers. These synthetic mouse-wheel events are sent in batches of 10-20 events with Y-deltas as fractional decimal numbers (0.01-0.1). So zooming the map by scrolling does not work as expected on Touchpad.

This commit introduces a double accumulator variable `_mouseWheelPos` that is used to sum individual Y-deltas as they are received and trigger zoom at integer steps only.

Related info and solution from: https://github.com/mrkite/minutor/issues/224

### CODE REVIEW

**Comment by yapus** [comment]
HI @janusw @tmijieux @bertt 
please check/merge this - i'm really looking forward for this to be part of next nuget package release (4.0.0-beta6?)

**Comment by inforithmics** [comment]
The Build failures are unrelated and are fixed here https://github.com/Mapsui/Mapsui/pull/1722

**Comment by inforithmics** [comment]
The build failures are unrelated and are fixed here.

https://github.com/Mapsui/Mapsui/pull/1722

I tested it and on the other platforms the Y value changes only 1 plus or -1 so my comments don't need to be adressed (so merging this now)

**Review by inforithmics — APPROVED** [review]

**Comment by yapus** [comment]
any idea when the next beta release would be published?

**Comment by yapus** [comment]
@inforithmics Hi, was this been reverted for some reason? Can't see these fixes in the latest 4.0.0-beta11

**Comment by yapus** [comment]
Should i fix it again and send new PR? The zoom not working with touchpad is really-really annoying....

**Comment by inforithmics** [comment]
Yes would be nice to send a new PR? The mouse handling moved to the navigator and your code got optimized away. 

https://github.com/Mapsui/Mapsui/commit/ce0f5edee10fffcf424d776318853d9e097c863f

**Comment by yapus** [comment]
I see, so what you think would be better solution here - put that logic back to the MapControl, or change `mouseWheelDelta` type to double and handle that logic in Navigator?

**Comment by inforithmics** [comment]
In my opinion I would handle this in MapControl. Because I think this is an Avalonia specific Problem.

**Comment by yapus** [comment]
Ok, see new pull request [pull/1984](https://github.com/Mapsui/Mapsui/pull/1984) please

**Pull request merged**
