### PR TITLE
update the dependencies on Svg.Skia in the nuspec files

### PR DESCRIPTION
**Pull request by janusw**
* using the latest version
* matching the package refs in Mapsui.Rendering.Skia etc
* this is supposed to fix issue #1211

### CODE REVIEW

**Comment by pauldendulk** [comment]
General comment: This is a common problem and this is the kind of maintenance I was referring to in an earlier comment. If the nuget is directly generated from the csproj this problem is mitigated.

**Review by pauldendulk — COMMENTED** [review]
Svg.Skia is a packagereference to Mapsui, not to the Mapsui.Native project, so I would think it should not be in Mapsui.Native at all. I comes indirectly from the Mapsui package. Perhaps I am wrong, but then I would like to know why it is needed.

**Comment by pauldendulk** [comment]
Another general comment. When we upgrade to a minor or patch of some package there is usually a reason for that, It fixes a bug of some sort. So the users should also get this upgraded version when installing the package. If the the lower limit of the version is not upgraded they will get the lowest version installed. So, we should always keep the lower version in sync with the installed version in the project (or generate from the csproj).

**Comment by janusw** [comment]
> Svg.Skia is a packagereference to Mapsui, not to the Mapsui.Native project, so I would think it should not be in Mapsui.Native at all.

True. I am removing it in #1214 (along with two other deps of the same kind).

**Comment by janusw** [comment]
> So, we should always keep the lower version in sync with the installed version in the project (or generate from the csproj).

I was not sure about this, because I thought it might be better to keep compatibility with lower versions (if possible), in case someone has a reason to stick with the lower version.
But yes, it seems like nuget always uses the lowest possible version, and I agree that it's probably better to bump the nuspec dep together with the package ref then. (Will do this for future updates.)

**Review by pauldendulk — APPROVED** [review]
Upgrade is necessary. Mapsiu.Native will be removed after this MR, thats no problem.

**Pull request merged**
