### PR TITLE
fix #1144 (ShapeFile.cs)

### LINKED ISSUE #1144: Shapefile.GetObjectIDsInView throw Exception as database is closed
What is correct use of Shapefile .GetObjectIDsInView ?

Code extract:
```
    if (!_isOpen)
                throw (new ApplicationException("An attempt was made to read from a closed datasource"));
```
How am I supposed to open it ?

Thanks for your help

### PR DESCRIPTION
**Pull request by franky235**
GetObjectIDsInView and GetGeometry are concerned public but cannot be used externally
I applied the exact same solution than GetFeature by creating two private additional methods (GetObjectIDsInViewPrivate and GetGeometryPrivate) in order to manage the Open and lock issue

### CODE REVIEW

**Review by janusw — APPROVED** [review]
This looks completely reasonable to me. Thanks for the contribution!

**Comment by janusw** [comment]
Note: You should sign the CLA, before we can merge this!

**Comment by franky235** [comment]
Adding another commit, not sure if I need an new PR, look it is added to this PR which was not my intention ...

**Comment by janusw** [comment]
> Adding another commit, not sure if I need an new PR, look it is added to this PR which was not my intention ...

Well, if you have an open PR on one of your branches, anything you add to the branch is automatically added to the PR as well.

What is your motivation for disabling the MouseMove handler?

**Comment by franky235** [comment]
Thanks for your explanation, I use git for years but not PR.

Removing temporarily MouseMove handler is convenient to draw something on the map with left clic, and probably also to reassigne left clic as requested here: https://stackoverflow.com/questions/52260870/change-the-panning-button-in-mapsui-control (seems it is not possible to remove events when you are not the owner)

**Comment by janusw** [comment]
> Removing temporarily MouseMove handler is convenient to draw something on the map with left clic, and probably also to reassigne left clic as requested here: https://stackoverflow.com/questions/52260870/change-the-panning-button-in-mapsui-control (seems it is not possible to remove events when you are not the owner)

Ok, this is really a separate issue and has nothing to do with the ShapeFile support, therefore I'd recommend to put it into a separate branch/PR (in particular if additional changes are necessary), and remove the commit from this branch (by force-pushing).

**Comment by franky235** [comment]
Well well, accidentally removed all my commits and closed the PR.
Pushed my fix again in a new commit, does not re-open the PR
Sorry for the mess, please advise ....

**Comment by janusw** [comment]
Huh, I guess you should just open a new PR.

Also I noticed that you opened this PR from your master branch. I'm not sure if this is such a good idea (e.g. because force-pushing can be a problem with master, etc). I'd recommend to create another branch (it could be named 'fix_shapefile' or similar) and use that for the PR.

**Comment by franky235** [comment]
Done, 
Thanks for the advice. I fully agree with the process (two PR and not using master branch) 
Was my intention but I have poor experience with Github interface, sorry for that :-(

**Pull request closed without merging**
