### PR TITLE
Fix OpenSeaSample and Sample Documentation

### PR DESCRIPTION
**Pull request by inforithmics**
Please summarize your PR and explain which problem it solves.

1. Fixed OpenSea Sample (use another Webservice)
2. Add Gebco_2021 Sample (the opensea sample used an gebco_2021 Image).
3. Fixed missing Samples Documentation.

### CODE REVIEW

**Comment by pauldendulk** [comment]
Somewhere else I use the open tile service pasted below, did you look into that? It seems to behave fine.

```csharp
private static HttpTileSource CreateTileSource(string userAgent)
{
    return new HttpTileSource(new GlobalSphericalMercator(),
        "https://tiles.openseamap.org/seamark/{z}/{x}/{y}.png",
        new[] { "a", "b", "c" }, name: "OpenSeaMap",
        userAgent: userAgent, persistentCache: DefaultCache);
}
```

**Comment by pauldendulk** [comment]
I will merge this if it is green.

**Comment by inforithmics** [comment]
To fix build Uno needs to be updated. Because the Uno GPU Pull request is green and there I upgraded Uno.

**Review by pauldendulk — APPROVED** [review]
Thanks

**Pull request merged**
