### PR TITLE
Change Padding for IconButtonWidget

### PR DESCRIPTION
**Pull request by charlenni**
Change padding from PaddingX and PaddingY to a MRect Padding for consistency with other widgets.
Change also background color of IconButtonWidget to transparent.

### CODE REVIEW

**Comment by pauldendulk** [comment]
@charlenni The rendering tests keep failing. I did not look into it, but it could be that some rendering tests actually detect a difference. I saw you changed something in transparency, perhaps that was the cause.

If the tests need fixing please take a look at the documentation on rendering tests again https://mapsui.com/documentation/rendering-tests.html.

The current rendering test mechanism tests all the samples. That is great. However, if a reference (original) image does not exist it will ignore that test. It is likely that there are some recent samples that do not have a reference image yet. If you run `scripts\test-image-copier.cmd` those images will show as added in the diff. It is okay to push them.

**Comment by charlenni** [comment]
I tested it before upload and now again. All tests worked. So it is the normal SkiaSharp crash because of threading (see #2425).

**Comment by pauldendulk** [comment]
The regression tests have been flaky since we added tests for all samples using discovery (It added a huge number of tests at once and was a very important improvement). A number of the flaky issues have been fixed (some real bugs). Currently the cross-thread rendering issue is still open, so it can crash sometimes. 

I need to know if a PR introduces a failing test or not. How I work with this flakyness is to re-run the windows tests to fix it. I try not to dig into the build log because I am already short on time. Sometimes I need to re-run it twice.  At some point it is green and I can assume it failed because of flakiness. But this PR is still red after running it for about four times, if it does not turn green ever I will have to look into the details of the log.

**Comment by pauldendulk** [comment]
Later PRs were green right away:

image

**Comment by pauldendulk** [comment]
btw, I the past I have noticed that the regression tests, which do a pixel by pixel compare with a small tolerance, can have different result from time to time. That was why the tolerance was introduced. I can not explain this difference, I would expect identical results. Perhaps it is a lurking bug in Skia, SkiaSharp or Mapsui. The difference is bigger between mac/linux/windows runs. So, if you run the tests on a mac they could fail on the windows build server, and you may need to update an image. btw, many images will be different, but only update the ones that actually fail.

**Comment by charlenni** [comment]
@pauldendulk I have to apologize. It was my fault. The problem was, that I missed to push two commits that I made after creating the PR. When I checked it the last time, all the tests running correct, because the two commits solved the problem. So on my PC all worked perfect.

I now pushed the two missing commits and expect, that it will running.

**Comment by charlenni** [comment]
I had one time, where the map had changed. There vanished a town, so that the image was different.

I would say, that the regression tests work perfect and are a very good for testing. But I found, that some of them were not correct. They missed the attribution.

**Comment by pauldendulk** [comment]
Yes, if the tests depend the osm service the data could just change. I think Thomas partially resolved this by working with caching.

**Comment by charlenni** [comment]
Ok, Mac fails because it needs a newer version of XCode :-( @inforithmics Anything we can do?

**Comment by charlenni** [comment]
Ok, now the regression tests work

**Review by pauldendulk — APPROVED** [review]
Makes sense.

**Pull request merged**
