### PR TITLE
Added a NeedsRefresh flag to DataChangedEventArgs

### PR DESCRIPTION
**Pull request by charlenni**
Added a NeedsRefresh flag to DataChangedEventArgs. With this, it is possible, that MemoryLayer isn't refreshed all the time.
Removed a debug WriteLine for Forms implementation.

### CODE REVIEW

**Comment by pauldendulk** [comment]
Perhaps MemoryLayer should not call DataChanged at all. What purpose would it have? 

The fact that it is called probably means something depends on the event. Perhaps that should be solved in a different way. What breaks if we remove the OnDataChanged on RefreshData.

**Comment by charlenni** [comment]
But even the data of a MemoryLayer could change. Or isn't this possible?

**Comment by pauldendulk** [comment]
Yes, but then it should call DataChanged when it actually changes. Not just when RefreshData is called and nothing changes. 

I now think I can remember I used RefreshData to trigger a refresh from the Navigator. After recent changes Refresh is evoked through a callback. So, I think we should just remove the MemoryLayer OnDataChanged and fix any issues that might follow from this, if any.

The WritableLayer has a SignalDataChanged to trigger OnDataChanged. It seemed like a workaround when I added it. A better solution might be that a Layer encapsulates the data and triggers OnDataChanged itself. But lets just add DataHasChanged() methods to the ILayer and IProvider interfaces so a refresh could be triggered from anywhere.

**Comment by pauldendulk** [comment]
I plan to add the DataHasChanged() method soon, and remove the DataChanged event in the MemoryLayer. Because of this the NeedsRefresh field in this PR will not be useful anymore, but perhaps there are other changes in this PR you would like to commit. Perhaps you could create a new PR for that.

**Comment by pauldendulk** [comment]
Also important. The fact that iOS gets performance problems because of too many invalidate call is a bug in itself. Perhaps in SkiaSharp.Views or Xamarin.

**Comment by pauldendulk** [comment]
I'll close this one. If there is anything else in this MR that needs merging please add it to another MR.

**Comment by charlenni** [comment]
Thank you for reviewing this.

Perhaps @Sebastian1989101 could test the next beta and report, if the screen update is fast enough.

**Pull request closed without merging**
