### PR TITLE
Update system text json to version 9.0.0

### PR DESCRIPTION
**Pull request by inforithmics**

### CODE REVIEW

**Review by pauldendulk — COMMENTED** [review]
What led you to make this change?

**Comment by IldarKhayrutdinov** [comment]
@pauldendulk I was asking https://github.com/Mapsui/Mapsui/discussions/2808

**Comment by pauldendulk** [comment]
@IldarKhayrutdinov And why do you need that? Is that the only thing blocking the use of .net9?

**Comment by Haukinger** [comment]
If I add a direct dependency in my app, it seems to work fine with net9, as far as I have tested by now.

**Comment by IldarKhayrutdinov** [comment]
Yes, I have direct dependency. System.Text.Json v9.0.0 supports .net8, there are no obstacles to using v9.0.0 in mapsui (on .net8).

**Review by pauldendulk — APPROVED** [review]

**Pull request merged**
