### PR TITLE
Mapsui.Samples.Forms.Mac: fix project configurations

### PR DESCRIPTION
**Pull request by janusw**
This PR should fix issue #1051. It particular it makes the build in Debug config work by setting the correct target architecture.

Furthermore, it enables the project for the platforms AnyCPU, x64 and x86, but disables it for ARM and iPhone.

### CODE REVIEW

**Comment by charlenni** [comment]
There seems to be an error. See https://ci.appveyor.com/project/pauldendulk/mapsui/builds/37433975#L1014

**Comment by janusw** [comment]
> There seems to be an error. See https://ci.appveyor.com/project/pauldendulk/mapsui/builds/37433975#L1014

True. But I don't think this error is related to my changes here. Instead it seems to occur with all recent PRs (all those from 2021?), starting with #1046.

The error message says:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(3466,5):
error APPX0108: The certificate specified has expired.
For more information about renewing certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.
[C:\projects\mapsui\Samples\Mapsui.Samples.Uwp\Mapsui.Samples.Uwp.csproj]
```

The mentioned website http://go.microsoft.com/fwlink/?LinkID=241478 is about "Signing an app package (Windows Store apps)", and it also contains instructions for renewing a certificate:
https://docs.microsoft.com/en-us/previous-versions/br230260(v=vs.110)?redirectedfrom=MSDN#renewing-a-certificate

**Comment by pauldendulk** [comment]
Thanks for pointing to the specific instructions. I pushed new keys for the two UWP project and the build is now green https://ci.appveyor.com/project/pauldendulk/mapsui/builds/37510021

**Comment by janusw** [comment]
> I pushed new keys for the two UWP project and the build is now green 

Great, thanks. 👍
I'll rebase the branch, in order to see if it is also green now.

**Comment by janusw** [comment]
Alright, all three PRs of mine are green now (after rebasing). Nice 😄

**Review by pauldendulk — APPROVED** [review]
I am quite unfamiliar with the mac side of things. Thanks for taking care of this.

**Pull request merged**
