### PR TITLE
Github: Maximum test duration 25s

### PR DESCRIPTION
**Pull request by inforithmics**
Set the maximum Test duration to 25s.

### CODE REVIEW

**Review by pauldendulk — COMMENTED** [review]
This PR sets `include-prerelease: false`. What problem did you run into that made you make this change? When I worked with the yml previous weeks I had warnings that `include-prerelease` was not known and I was about to delete. I just googled specifically for `include-prerelease` and get no results. Did you find any documentation about this?

**Comment by inforithmics** [comment]
Include-prerelease can be deleted. It is used for getting preview .net sdks. But because .net 8 is released this isn’t necessary. I will change the pull request accordingly.

**Comment by inforithmics** [comment]
include-prerelease: false is now removed

**Review by pauldendulk — APPROVED** [review]
👍

**Pull request merged**
