### PR TITLE
Fix jagged background for labels and widgets

### PR DESCRIPTION
**Pull request by pauldendulk**

### CODE REVIEW

**Comment by pauldendulk** [comment]
> Are there maybe more SkPaint Colors that need antialising?

Likely. But I think not every draw method benefits from it, and there is a performance penalty we may not always want to take. For instance, for drawing bitmaps there is the FilterQuality and we use FilterQuality.Low, while there is also High and Medium. For my purpose (some years ago) High was too slow. Btw, if you do not set the FilterQuality the default None is used, which is significantly worse than Low.

**Comment by inforithmics** [comment]
Yes, I thought about a configurable option could be helpful. I didn't see the problem because I have a 4K Monitor so Rounded Corners are smooth even without AntiAliasing and Smartphones have high Resolution too so you don't see much of a difference. But the Performance could be noticable. 

Maybe the MapControl could have two Properties Antialiasing and FilterQuality with Antialiasing set to true and FilterQuality set to FilterQuality.Low.

Or maybe this can be set with Properties on the Renderer.

**Comment by charlenni** [comment]
Is this nothing, that should be configurable for each layer or widget and not globally?

**Comment by pauldendulk** [comment]
@charlenni @inforithmics I created an issue to discuss this https://github.com/Mapsui/Mapsui/issues/2213

**Pull request merged**
