### PR TITLE
add getting started uwp

### PR DESCRIPTION
**Pull request by bertt**
add getting started uwp

### CODE REVIEW

**Comment by pauldendulk** [comment]
The WPF getting started was recently updated:
https://mapsui.com/documentation/getting-started-wpf.html

**Comment by pauldendulk** [comment]
@bertt Your other PR was merged which caused a conflict. Could you rebase?

**Comment by pauldendulk** [comment]
Also, there is problem with the build that I don't understand. Both the PR and the branch are built, what is the difference.
image

This is the problem:
image

**Comment by bertt** [comment]
merge conflict is fixed, only the AppVeyor is complaining about something

**Comment by bertt** [comment]
auth stuff?

```
warning: url has no scheme: ?
fatal: credential url cannot be parsed: ?
remote: No anonymous write access.
fatal: Authentication failed for 'https://github.com/Mapsui/Mapsui.git/'
Command exited with code 128
```

**Comment by pauldendulk** [comment]
Probably, but why is the problem not here: https://github.com/Mapsui/Mapsui/pull/1209

**Review by pauldendulk — APPROVED** [review]

**Pull request merged**
