### PR TITLE
Rewrite projections.md

### PR DESCRIPTION
**Pull request by pauldendulk**
Asked chatgpt to rewrite the projections page. I have not reviewed this myself. Created a merge request to make reviewing easier.

### CODE REVIEW

**Comment by charlenni** [comment]
Good improvement.

What I'm missing is a explanation of the internal coordinate system of Mapsui. Even if you set Mapsui.CRS you have other coordinates for the features.

**Comment by charlenni** [comment]
And MapInfo coordinates are in Map.CRS coordinate system? So, if I set it to SphericalMercator, I get all results of taps in SphericalMercator? That is not clear enough.

**Comment by pauldendulk** [comment]
I intended to add further improvements as suggested but I did not find time for it. So, I will merge this now and improve on it later. The coordinate system thing is indeed one of the most confusing things for new users.

**Comment by pauldendulk** [comment]
Also see https://www.youtube.com/watch?v=xZxwlisfeK0&t=20s

**Pull request merged**
