### PR TITLE
Implement workaround for missing callout in Blazor with workaround #2014

### PR DESCRIPTION
**Pull request by pauldendulk**
- Add a simple test to show a callout
- Fix the missing callout in Blazor by adding a workaround suggested here: 
   - https://github.com/mono/SkiaSharp/issues/1725#issuecomment-978843629

The workaround fixes the problem for our sample but our users will have to apply the same workaround. 

How to apply the workaround.
- Add this to the csproj of your main project 
```xml
<ItemGroup>
  <NativeFileReference Include="libHarfBuzzSharp.a" />
</ItemGroup>
```
- Now you need to copy that file to your project. For this you need to download the nuget package https://www.nuget.org/packages/HarfBuzzSharp.NativeAssets.WebAssembly/
- Unzip the nuget. 
- Copy the file from this folder `build\netstandard1.0\libHarfBuzzSharp.a\2.0.23` to you project folder.

### CODE REVIEW

**Comment by pauldendulk** [comment]
A real fix would deploy libHarfBuzzSharp automatically. I would except that adding HarfBuzzSharp.NativeAssets.WebAssembly to the csproj should solve the problem, but it did not.

**Comment by pauldendulk** [comment]
@inforithmics I would expect HarfBuzzSharp.NativeAssets.WebAssembly to the samples csproj should fix the problem. What do you think? Did I miss something? If not if will submit a bug or question in SkiaSharp.

**Comment by inforithmics** [comment]
https://github.com/mono/SkiaSharp/issues/1725

**Comment by inforithmics** [comment]
here in this pull request I added a targets file.
https://github.com/Mapsui/Mapsui/pull/1856

and included it in the nuget package. So maybe we could make a blazor.targets file.

```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	</ItemGroup>
		<NativeFileReference Include="libHarfBuzzSharp.a" />
	</ItemGroup>
</Project>

```
and add it to the nuget.

```
<!--target to add Harfbuzzsharp.NativeAssets.Webassembly -->
  <ItemGroup>
    <None Include="Mapsui.Forms.targets" PackagePath="build/net6.0/Blazor.targets" Pack="true" />
    <None Include="Mapsui.Forms.targets" PackagePath="build/net7.0/Blazor.targets" Pack="true" />
  </ItemGroup>

```


https://github.com/Mapsui/Mapsui/pull/1856

**Review by inforithmics — APPROVED** [review]
Nice that a specific sample is added

Testet it and it works. The targets approach I have to test if it works

**Comment by pauldendulk** [comment]
> https://github.com/mono/SkiaSharp/issues/1725
> And I applied the workaround here in the csproj
> https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Uno/Mapsui.Samples.Uno.Wasm/Mapsui.Samples.Uno.Wasm.csproj
> in the uno.winui.wasm too.

I found my workaround on that same thread. The one use used for Uno did not work for Blazor (just tested again, it still does not work). I had to use the one mentioned earlier in the thread. 

Let's add the targets file like you proposed because now everyone of our users has to find that same obscure thread to fix their problem.

**Pull request merged**
